openapi: 3.1.0
info:
  version: 1.0.0
  title: <Contacts Web App>
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    Contacts Web App is a web application for managing user contacts.
    The app allows users to register, log in, add, edit, delete and view contacts. The application also supports integration with Google OAuth for user authorization.
tags:
  #Users
    description: Operations with users (registration, login, exit, etc.)
  #Contacts
    description: Operations with contacts (adding, editing, deleting, viewing)
servers:
  - url: <http://localhost:3000>
  - url: #посилання на задеплоєний сайт
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
