openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Web App
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    Contacts Web App is a web application for managing user contacts.
    The app allows users to register, log in, add, edit, delete and view contacts. The application also supports integration with Google OAuth for user authorization.
tags:
  - name: Auth
    description: Operations with users (registration, login, exit, etc.)
  - name: Contacts
    description: Operations with contacts (adding, editing, deleting, viewing)
servers:
  - url: https://nodejs-hw-mongodb-aafz.onrender.com
  description: Production server
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register_post.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login_post.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh_post.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email_post.yaml'
  /auth/reset-password:
    post:
      $ref: '../swagger/paths/auth/reset-password_post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout_post.yaml'
  /contacts:
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
    get:
      $ref: ../swagger/paths/contacts/get.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
components:
  schemas:
    Contact:
      $ref: './swagger/components/schemas/contact.yaml'
    User:
      $ref: './swagger/components/schemas/user.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
